export const scenarios = [
  {
    id: 'empty-and-setup-states',
    title: 'Empty and setup states',
    description: 'Use these patterns when a workflow has no data yet, needs first-run guidance, or is waiting on local work to finish.',
    group: 'Workflow states',
    whenToUse: 'Choose these calm surfaces when the user is not blocked by an error and needs one clear next step.',
    examples: [
      {
        id: 'first-run-empty-panel',
        title: 'First-run empty panel',
        preview: 'EmptySetupPreview',
        components: ['EmptyState', 'Surface'],
        sampleState: { data: 'No findings yet', action: 'Run one focused scout' },
        props: { title: 'No findings yet', icon: 'search', actionLabel: 'Run scout' },
        notes: ['Use action copy that names the next product step.', 'Keep empty states calm; avoid warning colors unless the user is blocked.'],
      },
      {
        id: 'waiting-for-results',
        title: 'Waiting for results',
        preview: 'EmptySetupPreview',
        components: ['LoadingSkeleton', 'Surface'],
        sampleState: { data: 'Scout run in progress', action: 'Wait for deterministic local state' },
        props: { type: 'card', count: 1 },
        notes: ['Use skeletons for short-lived loading, not permanent empty states.', 'Keep the surrounding copy explicit about what is loading.'],
      },
      {
        id: 'guided-first-value',
        title: 'Guided first value prompt',
        preview: 'EmptySetupPreview',
        components: ['TourCallout'],
        sampleState: { data: 'Starter workflow incomplete', action: 'Open checklist' },
        props: { title: 'Reach first value', actionLabel: 'Open checklist' },
        notes: ['Use a single primary prompt for first-value guidance.', 'Do not stack multiple onboarding cards in one viewport.'],
      },
    ],
  },
  {
    id: 'finding-review-cards',
    title: 'Finding review cards',
    description: 'Use these cards when scanning candidate posts, comparing signal strength, or selecting findings for reports.',
    group: 'Research review',
    whenToUse: 'Choose finding cards for compact, repeatable summaries of source, status, score, and engagement signal.',
    examples: [
      {
        id: 'high-score-finding',
        title: 'High-score finding',
        preview: 'FindingReviewPreview',
        components: ['FindingCard', 'PostCard'],
        sampleState: { status: 'starred', score: '9.2', source: 'Reddit' },
        props: { selected: false, projectMode: 'research' },
        notes: ['Use high scores to aid ordering; do not rely on color alone.', 'Preserve source and engagement badges for scanning.'],
      },
      {
        id: 'selected-research-finding',
        title: 'Selected research finding',
        preview: 'FindingReviewPreview',
        components: ['FindingCard', 'PostCard'],
        sampleState: { status: 'new', score: '7.4', source: 'Bluesky' },
        props: { selected: true, projectMode: 'research', checked: true },
        notes: ['Use selected state only for the active detail-panel item or bulk selection.', 'Keep callbacks local in previews; production selection belongs to app state.'],
      },
      {
        id: 'low-signal-finding',
        title: 'Low-signal finding',
        preview: 'FindingReviewPreview',
        components: ['FindingCard', 'PostCard'],
        sampleState: { status: 'excluded', score: '2.1', source: 'Reddit' },
        props: { selected: false, projectMode: 'research' },
        notes: ['Excluded cards should stay visible enough to audit decisions.', 'Avoid making low-signal states visually louder than high-signal states.'],
      },
    ],
  },
  {
    id: 'workspace-context',
    title: 'Workspace context',
    description: 'Use shell-adjacent context components to orient contributors around the active project, current view, and report state.',
    group: 'Workspace shell',
    whenToUse: 'Use these components near navigation or side panels when the user needs lightweight context instead of another page.',
    examples: [
      {
        id: 'top-context-breadcrumb',
        title: 'Top context breadcrumb',
        preview: 'WorkspaceContextPreview',
        components: ['TopContextBar'],
        sampleState: { project: 'AI Note Taking Research', view: 'posts' },
        props: { projectName: 'AI Note Taking Research', view: 'posts' },
        notes: ['Keep breadcrumbs short and product-facing.', 'Use actions sparingly so the top bar stays scannable.'],
      },
      {
        id: 'insight-pane-no-report',
        title: 'Insight pane without report',
        preview: 'WorkspaceContextPreview',
        components: ['InsightPane', 'Surface'],
        sampleState: { queries: '5 active', report: 'None selected' },
        props: { enabledQueryCount: 5, filterSummary: 'Showing: new · reddit' },
        notes: ['Use the empty report hint to explain why the pane is quiet.', 'Keep status summaries factual and compact.'],
      },
      {
        id: 'insight-pane-active-report',
        title: 'Insight pane with active report',
        preview: 'WorkspaceContextPreview',
        components: ['InsightPane', 'Surface'],
        sampleState: { queries: '5 active', report: 'Recurring Meeting Notes Pain Points' },
        props: { selectedReport: 'Recurring Meeting Notes Pain Points' },
        notes: ['Use active report context when findings are filtered or interpreted through a report.', 'Do not put full report content in the insight pane.'],
      },
    ],
  },
  {
    id: 'modal-decisions',
    title: 'Modal decisions',
    description: 'Use modal patterns for constrained decisions, credential guidance, and short review flows that should not become full pages.',
    group: 'Decision flows',
    whenToUse: 'Use modals only when the user must make or dismiss a focused decision before continuing the current workflow.',
    examples: [
      {
        id: 'confirmation-modal',
        title: 'Confirmation decision',
        preview: 'ModalDecisionPreview',
        components: ['Modal'],
        sampleState: { decision: 'Archive one finding', result: 'Local no-op buttons' },
        props: { open: true, title: 'Archive finding' },
        notes: ['Use concise titles that name the decision.', 'Keep destructive and safe actions visually distinct.'],
      },
      {
        id: 'credential-guidance-modal',
        title: 'Credential guidance',
        preview: 'ModalDecisionPreview',
        components: ['GoogleLockedNotice', 'Modal'],
        sampleState: { provider: 'Parallel.ai', key: 'PARALLEL_API_KEY missing' },
        props: { open: true, showViewExistingReports: true },
        notes: ['Explain why the feature is unavailable before listing setup steps.', 'Keep external links explicit and leave existing saved data accessible.'],
      },
    ],
  },
];
